template: |
  <!-- Recent GitHub Activity:START -->
  {{#each activity}}
  - {{this.type}} - [{{this.repo.name}}]({{this.repo.url}}) - {{this.created_at}}
    - {{this.payload.action || 'N/A'}}: {{this.payload.issue?.title || this.payload.pull_request?.title || 'No title'}}
  {{/each}}
  <!-- Recent GitHub Activity:END -->

# Update the README.md file
readme_path: ./README.md

# Maximum number of events to show
max_events: 5

# GitHub username
github_username: PhilipKone

# Types of events to include
include_events:
  - IssuesEvent
  - PullRequestEvent
  - PushEvent
  - CreateEvent
  - ForkEvent
  - WatchEvent
